@Library("jenlib") _

boolean executeHwTests = [
               !isTriggeredByGerrit(),
               env.GERRIT_PROJECT == "hxtorch",
               env.GERRIT_PROJECT == "grenade",
].any({ it })

Map<String, Object> pipelineOptions = [
		projects: ["hxtorch"],
		container: [app: "dls-core"],
		moduleOptions: [modules: ["ppu-toolchain"]],
		notificationChannel: "#dls-software"
]

if (executeHwTests) {
	pipelineOptions << [
			testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 0, reservation: "pdauer_33"],
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1",
			postTestHook: { archiveArtifacts artifacts: "hxtorch/tests/hw/plots/*", allowEmptyArchive: true },
	]
}

withCcache() {
    wafDefaultPipeline(pipelineOptions)
}
